@baseURL = http://localhost:8080

###
# @name ping
GET {{baseURL}}/ping

###
# @name add-transaction
POST {{baseURL}}/transaction

###
# @name remove-transaction
DELETE {{baseURL}}/transaction/1

###
# @name history
GET {{baseURL}}/transactions